version: '3'

services:
  backend:
    build: backend
    ports:
      - 8005:8005
    environment:
      MAX_WORKERS: "1"
      API_BASE_URL: v1
      OPENAI_KEY: 'your chatgpt key here'
  frontend:
    build: frontend
    ports:
      - '8006:80'
    volumes:
      # - ./frontend/app:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # proxy_pass http://backend:8005;
    links:
      - backend